### ISSUE TITLE
Does this plugin include reports on the number of times a product has been bought?

### ISSUE THREAD

**Issue by kevadamson** [barrelstrength/craft-sprout-reports-commerce#6]
^ What the title asks :)

**Comment by BenParizek** [comment]
@kevadamson The Commerce Product Revenue report has a "Quantity Sold" column.

Feel free to test it out with the free trial of Sprout Reports and see if it works for you. If not, we're happy to consider feature requests and, as an alternative, Sprout Reports has custom report options that can be built-in Twig and MySQL and PHP – wherever your comfort may lie.
